<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        \App\Models\User::create([
            'id' => 'admin@gmail.com',
            'email' => 'admin@gmail.com',
            'password' => Hash::make('123456'),
            'name' => 'علي وليد داود عواد',
            'department' => 'حاسوب',
            'college' => 'كلية العلوم',
            'certificate' => 'دكتوراه',
            'identification_number'=>'12345',
            'general_jurisdiction' => 'علوم حاسوب',
            'exact_jurisdiction' => 'تقنية معلومات',
            'current_promotion' => 'مدرس مساعد',
            'date_current_promotion' => '2020-12-12',
            'user' => false,
            'supervisor' => false,
            'Leader' => false,
            'Admin' => true,
            'first_member' => false,
            'second_member' => false,
            'third_member' => false,
            'forth_member' => false,
            'fifth_member' => false,
        ]
        );
        \App\Models\User::create([
            'id' => 'leader@gmail.com',
            'email' => 'leader@gmail.com',
            'password' => Hash::make('123456'),
            'name' => 'عباس عبد العزيز عبد الحميد',
            'department' => 'حاسوب',
            'college' => 'كلية العلوم',
            'certificate' => 'دكتوراه',
            'identification_number'=>'12345',
            'general_jurisdiction' => 'علوم حاسوب',
            'exact_jurisdiction' => 'تقنية معلومات',
            'current_promotion' => 'مدرس مساعد',
            'date_current_promotion' => '2020-12-12',
            'user' => false,
            'supervisor' => false,
            'Leader' => true,
            'Admin' => false,
            'first_member' => false,
            'second_member' => false,
            'third_member' => false,
            'forth_member' => false,
            'fifth_member' => false,
        ]
        );
        \App\Models\User::create([
            'id' => 'super@gmail.com',
            'email' => 'super@gmail.com',
            'password' => Hash::make('123456'),
            'name' => 'بشار مكي العيساوي',
            'department' => 'حاسوب',
            'college' => 'كلية العلوم',
            'certificate' => 'دكتوراه',
            'identification_number'=>'12345',
            'general_jurisdiction' => 'علوم حاسوب',
            'exact_jurisdiction' => 'تقنية معلومات',
            'current_promotion' => 'مدرس مساعد',
            'date_current_promotion' => '2020-12-12',
            'user' => false,
            'supervisor' => true,
            'Leader' => false,
            'Admin' => false,
            'first_member' => false,
            'second_member' => false,
            'third_member' => false,
            'forth_member' => false,
            'fifth_member' => false,
        ]
        );
        \App\Models\User::create([
            'id' => 'asraa@gmail.com',
            'email' => 'asraa@gmail.com',
            'password' => Hash::make('123456'),
            'name' => 'اسراء جعفر باقر',
            'department' => 'حاسوب',
            'college' => 'كلية العلوم',
            'certificate' => 'دكتوراه',
            'identification_number'=>'12345',
            'general_jurisdiction' => 'علوم حاسوب',
            'exact_jurisdiction' => 'تقنية معلومات',
            'current_promotion' => 'مدرس مساعد',
            'date_current_promotion' => '2020-12-12',
            'user' => true,
            'supervisor' => false,
            'Leader' => false,
            'Admin' => false,
            'first_member' => false,
            'second_member' => false,
            'third_member' => false,
            'forth_member' => false,
            'fifth_member' => false,
        ]
        );
        \App\Models\User::create([
            'id' => 'jalal@gmail.com',
            'email' => 'jalal@gmail.com',
            'password' => Hash::make('123456'),
            'name' => 'جلال حميد عواد',
            'department' => 'حاسوب',
            'college' => 'كلية العلوم',
            'certificate' => 'دكتوراه',
            'identification_number'=>'12345',
            'general_jurisdiction' => 'علوم حاسوب',
            'exact_jurisdiction' => 'معالجة صور',
            'current_promotion' => 'مدرس',
            'date_current_promotion' => '2020-12-12',
            'user' => true,
            'supervisor' =>false,
            'Leader' => false,
            'Admin' => false,
            'first_member' => false,
            'second_member' => false,
            'third_member' => false,
            'forth_member' => false,
            'fifth_member' => false,
        ]
        );
        \App\Models\User::create([
            'id' => 'muna@gmail.com',
            'email' => 'muna@gmail.com',
            'password' => Hash::make('123456'),
            'name' => 'منى عبد الحسين راضي',
            'department' => 'حاسوب',
            'college' => 'كلية العلوم',
            'certificate' => 'ماجستير',
            'identification_number'=>'12345',
            'general_jurisdiction' => 'علوم حاسوب',
            'exact_jurisdiction' => 'معالجة صور',
            'current_promotion' => 'مدرس',
            'date_current_promotion' => '2020-12-12',
            'user' => true,
            'supervisor' =>false,
            'Leader' => false,
            'Admin' => false,
            'first_member' => false,
            'second_member' => false,
            'third_member' => false,
            'forth_member' => false,
            'fifth_member' => false,
        ]
        );
        \App\Models\User::create([
            'id' => 'sunds@gmail.com',
            'email' => 'sunds@gmail.com',
            'password' => Hash::make('123456'),
            'name' => 'سندس عبدالامير حميد',
            'department' => 'حاسوب',
            'college' => 'كلية العلوم',
            'certificate' => 'دكتوراه',
            'identification_number'=>'12345',
            'general_jurisdiction' => 'علوم حاسوب',
            'exact_jurisdiction' => 'نظم تشغيل',
            'current_promotion' => 'استاذ مساعد',
            'date_current_promotion' => '2020-12-12',
            'user' => true,
            'supervisor' =>false,
            'Leader' => false,
            'Admin' => false,
            'first_member' => false,
            'second_member' => false,
            'third_member' => false,
            'forth_member' => false,
            'fifth_member' => false,
        ]
        );
        \App\Models\User::create([
            'id' => 'jamal@gmail.com',
            'email' => 'jamal@gmail.com',
            'password' => Hash::make('123456'),
            'name' => 'جمال ناصر حسون',
            'department' => 'حاسوب',
            'college' => 'كلية العلوم',
            'certificate' => 'دكتوراه',
            'identification_number'=>'12345',
            'general_jurisdiction' => 'علوم حاسوب',
            'exact_jurisdiction' => 'نظم تشغيل',
            'current_promotion' => 'استاذ مساعد',
            'date_current_promotion' => '2020-12-12',
            'user' => true,
            'supervisor' =>false,
            'Leader' => false,
            'Admin' => false,
            'first_member' => false,
            'second_member' => false,
            'third_member' => false,
            'forth_member' => false,
            'fifth_member' => false,
        ]
        );

        \App\Models\User::create([
            'id' => 'lajna1@gmail.com',
            'email' => 'lajna1@gmail.com',
            'password' => Hash::make('123456'),
            'name' => 'كمال حميد حسون',
            'department' => 'حاسوب',
            'college' => 'كلية العلوم',
            'certificate' => 'دكتوراه',
            'identification_number'=>'12345',
            'general_jurisdiction' => 'علوم حاسوب',
            'exact_jurisdiction' => 'نظم تشغيل',
            'current_promotion' => 'استاذ مساعد',
            'date_current_promotion' => '2020-12-12',
            'user' => true,
            'supervisor' =>false,
            'Leader' => false,
            'Admin' => false,
            'first_member' => false,
            'second_member' => false,
            'third_member' => false,
            'forth_member' => false,
            'fifth_member' => false,
        ]
        );

        \App\Models\User::create([
            'id' => 'lajna2@gmail.com',
            'email' => 'lajna2@gmail.com',
            'password' => Hash::make('123456'),
            'name' => 'محمد مصطفى جمال',
            'department' => 'حاسوب',
            'college' => 'كلية العلوم',
            'certificate' => 'دكتوراه',
            'identification_number'=>'12345',
            'general_jurisdiction' => 'علوم حاسوب',
            'exact_jurisdiction' => 'نظم تشغيل',
            'current_promotion' => 'استاذ مساعد',
            'date_current_promotion' => '2020-12-12',
            'user' => true,
            'supervisor' =>false,
            'Leader' => false,
            'Admin' => false,
            'first_member' => false,
            'second_member' => false,
            'third_member' => false,
            'forth_member' => false,
            'fifth_member' => false,
        ]
        );
    }
}
